/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.sena.yugi_api;

import java.awt.Image;
import java.net.URL;
import java.util.Random;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author USUARIO
 */
public class YuGi_Fight extends javax.swing.JFrame {
    private JSONObject[] jugadorCartas = new JSONObject[3];
    private JSONObject[] rivalCartas = new JSONObject[3];
    /**
     * Creates new form YuGi_Fight
     */
    public YuGi_Fight() {
        initComponents();
        
        try {
            JSONArray cartas = YuGi_APIHelper.getRandomCards(10);
            
             jugadorCartas = new JSONObject[] {
                cartas.getJSONObject(0),
                cartas.getJSONObject(1),
                cartas.getJSONObject(2)
            };

            rivalCartas = new JSONObject[] {
                cartas.getJSONObject(3),
                cartas.getJSONObject(4),
                cartas.getJSONObject(5)
            };
            
            jComboBox1.removeAllItems();
            for (int i = 0; i < jugadorCartas.length; i++) {
                jComboBox1.addItem(jugadorCartas[i].getString("name"));
            }
            for (int i = 0; i < 3; i++) {
                jugadorCartas[i] = cartas.getJSONObject(i);
                rivalCartas[i] = cartas.getJSONObject(i + 3);
            }

            mostrarCartasJugador();
            mostrarCartasRival();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelHome = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelCard1 = new javax.swing.JLabel();
        jLabelCard2 = new javax.swing.JLabel();
        jLabelCard3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelRival1 = new javax.swing.JLabel();
        jLabelRival2 = new javax.swing.JLabel();
        jLabelRival3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButtonAtk = new javax.swing.JButton();
        jButtonDef = new javax.swing.JButton();
        jButtonRestart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fight");

        jPanel1.setBackground(new java.awt.Color(203, 52, 34));

        jLabelHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Home.png"))); // NOI18N
        jLabelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHomeMouseClicked(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tus cartas"));

        jLabelCard1.setText("jLabel1");

        jLabelCard2.setText("jLabel2");

        jLabelCard3.setText("jLabel3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabelCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabelCard2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCard3, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelCard1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addComponent(jLabelCard3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCard2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Cartas del rival"));

        jLabelRival1.setText("jLabel4");

        jLabelRival2.setText("jLabel5");

        jLabelRival3.setText("jLabel6");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRival1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelRival2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelRival3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRival1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRival2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelRival3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Elije tu carta");

        jButtonAtk.setText("ATAQUE");
        jButtonAtk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtkActionPerformed(evt);
            }
        });

        jButtonDef.setText("DEFENSA");
        jButtonDef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDefActionPerformed(evt);
            }
        });

        jButtonRestart.setText("Reiniciar");
        jButtonRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabelHome))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jButtonAtk)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonDef))
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 17, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRestart)
                        .addGap(81, 81, 81))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelHome, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAtk)
                            .addComponent(jButtonDef))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jButtonRestart)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomeMouseClicked
        YuGi_API view = new YuGi_API();
        view.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jLabelHomeMouseClicked

    private void jButtonAtkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtkActionPerformed
        combatir("Ataque");
    }//GEN-LAST:event_jButtonAtkActionPerformed

    private void jButtonDefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDefActionPerformed
        combatir("Defensa");
    }//GEN-LAST:event_jButtonDefActionPerformed

    private void jButtonRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestartActionPerformed
        reiniciarJuego();
    }//GEN-LAST:event_jButtonRestartActionPerformed
    
    private String formatoCarta(JSONObject carta, JLabel label) {
        String nombre = carta.getString("name");
        int atk = carta.has("atk") ? carta.getInt("atk") : 0;
        int def = carta.has("def") ? carta.getInt("def") : 0;
        
        String urlImg = carta.getJSONArray("card_images").getJSONObject(0).getString("image_url");
        label.setIcon(obtenerImagen(urlImg));
        label.setHorizontalTextPosition(JLabel.CENTER);
        label.setVerticalTextPosition(JLabel.BOTTOM);
        
        return "<html>" + nombre + "<br>ATK: " + atk + "<br>DEF: " + def + "</html>";
    }
    
    public ImageIcon obtenerImagen(String urlImagen) {
        try {
            URL url = new URL(urlImagen);
            Image image = ImageIO.read(url);
            Image scaled = image.getScaledInstance(150, 220, Image.SCALE_SMOOTH); // Ajusta el tamaño
            return new ImageIcon(scaled);
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
    
    private void mostrarImagenCarta(JSONObject carta, JLabel label) {
        try {
            String urlImg = carta.getJSONArray("card_images").getJSONObject(0).getString("image_url");
            label.setIcon(obtenerImagen(urlImg));
            label.setText(""); // No texto, solo imagen
        } catch (Exception e) {
            label.setText("Error al cargar imagen");
        }
    }
    
    private void mostrarCartasJugador() {
        jLabelCard1.setText(formatoCarta(jugadorCartas[0], jLabelCard1));
        jLabelCard2.setText(formatoCarta(jugadorCartas[1], jLabelCard2));
        jLabelCard3.setText(formatoCarta(jugadorCartas[2], jLabelCard3));
    }

    private void mostrarCartasRival() {
        mostrarImagenCarta(rivalCartas[0], jLabelRival1);
        mostrarImagenCarta(rivalCartas[1], jLabelRival2);
        mostrarImagenCarta(rivalCartas[2], jLabelRival3);

    }
    
    private void combatir(String modoJugador) {
    int seleccion = jComboBox1.getSelectedIndex();
    
    if (seleccion < 0) {
        JOptionPane.showMessageDialog(this, "Selecciona una carta antes de combatir.");
        return;
    }

    JSONObject cartaJugador = jugadorCartas[seleccion];
    JSONObject cartaRival = rivalCartas[new Random().nextInt(3)];

    String nombreJugador = cartaJugador.optString("name", "Carta jugador");
    String nombreRival = cartaRival.optString("name", "Carta rival");

    int atkJ = cartaJugador.optInt("atk", 0);
    int defJ = cartaJugador.optInt("def", 0);
    int atkR = cartaRival.optInt("atk", 0);
    int defR = cartaRival.optInt("def", 0);

    String modoRival = Math.random() > 0.5 ? "Ataque" : "Defensa";

    String resultado;

    if (modoJugador.equals("Ataque") && modoRival.equals("Ataque")) {
        resultado = atkJ > atkR ? "Ganaste en Ataque" : "Perdiste en Ataque";
    } else if (modoJugador.equals("Ataque") && modoRival.equals("Defensa")) {
        resultado = atkJ > defR ? "Ganaste. Tu ataque superó la defensa" : "Peridste. Tu ataque fue bloqueado";
    } else if (modoJugador.equals("Defensa") && modoRival.equals("Ataque")) {
        resultado = defJ > atkR ? "Ganaste. Bloqueaste el ataque del rival" : " Perdiste. Tu defensa fue vencida";
    } else {
        resultado = defJ > defR ? "Ganaste. Tu defensa fue más fuerte" : "Empate defensivo.";
    }

    String mensaje = """
            Carta seleccionada: %s (%s: ATK %d / DEF %d)
            Carta rival: %s (%s: ATK %d / DEF %d)
            
            Resultado:
            %s
            """.formatted(
            nombreJugador, modoJugador, atkJ, defJ,
            nombreRival, modoRival, atkR, defR,
            resultado
    );

        JOptionPane.showMessageDialog(this, mensaje);
    }
    
    private void reiniciarJuego() {
        try {
            jButtonRestart.setEnabled(false);
            JSONArray cartas = YuGi_APIHelper.getRandomCards(10);
            jugadorCartas = new JSONObject[] {
                cartas.getJSONObject(0), cartas.getJSONObject(1), cartas.getJSONObject(2)
            };
            rivalCartas = new JSONObject[] {
                cartas.getJSONObject(3), cartas.getJSONObject(4), cartas.getJSONObject(5)
            };

            // Mostrar imágenes (asume que ya tienes este método)
            mostrarCartasJugador();
            mostrarCartasRival();

            // Llenar ComboBox
            jComboBox1.removeAllItems();
            for (int i = 0; i < jugadorCartas.length; i++) {
                jComboBox1.addItem(jugadorCartas[i].getString("name"));
            }

    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al reiniciar");
    }
     finally {
            jButtonRestart.setEnabled(true);
            
        }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YuGi_Fight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YuGi_Fight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YuGi_Fight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YuGi_Fight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YuGi_Fight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtk;
    private javax.swing.JButton jButtonDef;
    private javax.swing.JButton jButtonRestart;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCard1;
    private javax.swing.JLabel jLabelCard2;
    private javax.swing.JLabel jLabelCard3;
    private javax.swing.JLabel jLabelHome;
    private javax.swing.JLabel jLabelRival1;
    private javax.swing.JLabel jLabelRival2;
    private javax.swing.JLabel jLabelRival3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
